# Generated by Django 2.2.12 on 2020-06-13 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurusan', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('telepon', models.IntegerField()),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataSiswa.Jurusan')),
            ],
        ),
    ]
