# Generated by Django 2.2.12 on 2020-06-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataSiswa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='telepon',
            field=models.BigIntegerField(),
        ),
    ]
